### ISSUE TITLE
AttributeError: 'list' object has no attribute 'attrs'

### ISSUE THREAD

**Issue by ppiecuch** [BlameButton/disrupt#7]
I have a problem with one of my container - Image object does not have **attrs** field. Not sure why.
Regards
Pawel

[<Image: 'clementmouchet/datapusher:latest'>]

Traceback (most recent call last):
  File "main.py", line 165, in <module>
    main()
  File "main.py", line 52, in main
    update_services(client, apprise)
  File "main.py", line 81, in update_services
    outdated, tag, digest = is_service_outdated(client, service)
  File "main.py", line 122, in is_service_outdated
    remote_digest = get_image_digest(remote_image)
  File "main.py", line 157, in get_image_digest
    digests = image.attrs.get('RepoDigests')
AttributeError: 'list' object has no attribute 'attrs'

**Comment by bram-pkg** [comment]
Hello, @ppiecuch.

Sorry for the late reply, have been busy with work.

Can you provide more info, how you provisioned the containers? (docker-compose or docker cli, etc.)

**Comment by bram-pkg** [comment]
No response yet, closing.

**Comment by bram-pkg** [comment]
This should be fixed by 8b0d020d8e7bd60574ffb210feee768d6bf5f6bb.
